### ISSUE TITLE
NameError: name 'urbanature2' is not defined

### ISSUE THREAD

**Issue by jcuc** [jesusdanielcf/OdooUserPassChanger#1]
Thanks you for your code, but i have a problem with it. Can you help me?

Enter the DB name: urbanature2
Traceback (most recent call last):
  File "OdooUserPassChanger.py", line 19, in <module>
    dbname = input("Enter the DB name: ")
  File "<string>", line 1, in <module>
NameError: name 'urbanature2' is not defined

**Comment by 0xcomposure** [comment]
Hi @jcuc 

Which Python version are you using? In case that you're using Python 2, have you changed input to raw_input?

**Comment by jcuc** [comment]
Hello, it is versión 3.

El 12 sept. 2017 0:31, "alissonshell" <notifications@github.com<mailto:notifications@github.com>> escribió:

Hi @jcuc<https://github.com/jcuc>

Which Python version are you using? In case that you're using Python 2, have you changed input to raw_input?

**Comment by 0xcomposure** [comment]
Hi!

I just tried the script and is working right with Python 3 for me. I got the same error as you once I tried with Python 2.

I just created a Python 2 version of the script, can you try with that version in order to discard the Python version used by the system?

https://github.com/alissonshell/OdooUserPassChanger/blob/master/OdooUserPassChanger-python2.py

**Comment by jcuc** [comment]
Hello, you had a good job, python version is 2,7. Im sorry.

Thanks you and kind regars.



________________________________
De: alissonshell <notifications@github.com>
Enviado: martes, 12 de septiembre de 2017 2:19
Para: alissonshell/OdooUserPassChanger
Cc: jcuc; Mention
Asunto: Re: [alissonshell/OdooUserPassChanger] NameError: name 'urbanature2' is not defined (#1)


Hi!

I just tried the script and is working right with Python 3 for me. I got the same error as you once I tried with Python 2.

I just created a Python 2 version of the script, can you try with that version in order to discard the Python version used by the system?

https://github.com/alissonshell/OdooUserPassChanger/blob/master/OdooUserPassChanger-python2.py

**Comment by 0xcomposure** [comment]
I'm glad to read that it works right for you now!
If you have any other question or issue don't hesitate to ask.

Thank you!
